### ISSUE TITLE
0.3.0 Plan

### ISSUE THREAD

**Issue by Eskibear** [Eskibear/vscode-maven#10]
## Features to add
- [x] Support to import all maven projects under specified folder. https://github.com/Eskibear/vscode-maven/issues/9
- [x] Support to remove imported projects. https://github.com/Eskibear/vscode-maven/issues/15
- [x] Use a better extension icon. https://github.com/Eskibear/vscode-maven/issues/8

## Bugs to fix
- [x] Archetype catalog downloading issue. https://github.com/Eskibear/vscode-maven/issues/17

## Reference
Test Plan https://github.com/Eskibear/vscode-maven/issues/11
