### ISSUE TITLE
0.4.0 Plan

### ISSUE THREAD

**Issue by Eskibear** [Eskibear/vscode-maven#29]
## New features

- [x] auto search and import all project for each workspace. (https://github.com/Eskibear/vscode-maven/issues/30)
- [x] Support to specify `mvn` location not in `PATH` (https://github.com/Eskibear/vscode-maven/issues/12)
- [x] Provide better user experience to generate project from archetype. (https://github.com/Eskibear/vscode-maven/issues/34)
## Issue fixes
Refer to: https://github.com/Eskibear/vscode-maven/milestone/3

**Comment by Eskibear** [comment]
Completed.
